version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keja_hunt
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data: